# Generated by Django 3.2.23 on 2024-02-06 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('lesson_type', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Mock Test', 'Mock Test')], default='', max_length=20)),
                ('lesson_date', models.DateField(blank=True, null=True)),
                ('lesson_time', models.TimeField(blank=True, null=True)),
                ('house_no', models.CharField(default='', max_length=40)),
                ('street', models.CharField(default='', max_length=100)),
                ('town', models.CharField(default='', max_length=40)),
                ('post_code', models.CharField(default='', max_length=7)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=42.99, max_digits=6)),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('billpayer_name', models.CharField(default='', max_length=50)),
                ('billpayer_house_no', models.CharField(default='', max_length=40)),
                ('billpayer_street', models.CharField(default='', max_length=100)),
                ('billpayer_town', models.CharField(default='', max_length=40)),
                ('billpayer_post_code', models.CharField(default='', max_length=10)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='userprofile.userprofile')),
            ],
        ),
    ]
