# Generated by Django 3.2.23 on 2024-02-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Lesson Booking', 'verbose_name_plural': 'Lesson Bookings'},
        ),
    ]
