# Generated by Django 3.2.23 on 2024-02-21 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20240221_1144'),
        ('booking', '0006_remove_booking_stripe_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.price'),
        ),
    ]
