# Generated by Django 3.2.23 on 2024-02-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refunded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
