# Generated by Django 3.2.23 on 2024-02-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_price_lesson_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Lesson Price', 'verbose_name_plural': 'Lesson Prices'},
        ),
        migrations.AlterField(
            model_name='price',
            name='lesson_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, unique=True),
        ),
    ]
