# Generated by Django 3.2.23 on 2024-02-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20240221_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Lesson Price', 'verbose_name_plural': 'Lesson Price'},
        ),
        migrations.AlterField(
            model_name='price',
            name='lesson_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, unique=True),
        ),
    ]
