# Generated by Django 3.2.23 on 2024-02-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20240221_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
