# Generated by Django 3.2.23 on 2024-02-06 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('license_no', models.CharField(blank=True, max_length=25, null=True)),
                ('license_expiry', models.DateField(blank=True, default=None, null=True)),
                ('home_house_no', models.CharField(blank=True, max_length=40, null=True)),
                ('home_street', models.CharField(blank=True, max_length=100, null=True)),
                ('home_town', models.CharField(blank=True, max_length=40, null=True)),
                ('home_post_code', models.CharField(blank=True, max_length=7, null=True)),
                ('theory_test_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('theory_test_center', models.CharField(blank=True, choices=[('Alnwick', 'Alnwick'), ('Bishop Auckland', 'Bishop Auckland'), ('Hexham', 'Hexham'), ('Middlesbrough', 'Middlesbrough'), ('Newcastle', 'Newcastle'), ('Sunderland', 'Sunderland')], max_length=100, null=True)),
                ('mock_test_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('mock_test_address', models.TextField(blank=True, null=True)),
                ('practical_test_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('practical_test_center', models.CharField(blank=True, choices=[('Blyth', 'Blyth'), ('Darlington', 'Darlington'), ('Durham', 'Durham'), ('Gateshead', 'Gateshead'), ('Gosforth', 'Gosforth'), ('Hartlepool', 'Hartlepool'), ('Hexham', 'Hexham'), ('Middlesbrough', 'Middlesbrough'), ('Sunderland', 'Sunderland')], max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
