# Generated by Django 3.2.23 on 2024-02-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
